services:
  server:
    build: server
    ports:
      - "8000:8000"
    networks:
      - hsdle
  ws:
    build: .
    networks:
      - hsdle
      - proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

networks:
  hsdle:
  proxy:
    external: true
